### PR TITLE
Added screenshots of commit c974979 in dark and light mode.

### LINKED ISSUE #7: [DOC] Add Screenshots in README.md
## Description
Add screenshots of commit c974979 from my [profile page](https://github.com/Akshu-on-github/Akshu-on-github) at the top of the README.md of this repo:
- In Light Mode
- In Dark Mode

### Additional Context
Adding a screenshot of the realized version can:
- Help visualize the composition
- Identify customizable components

- [x] This issue has been assigned
- [x] The assignee has read the [Code of Conduct](CODE_OF_CONDUCT.md) and the [Contributing Guidelines](CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by saksham-s1ngh**
Added a title, and placed the screenshots side by side for a comparitive layout.

### CODE REVIEW

**Review by Akshu-on-github — CHANGES_REQUESTED** [review]
Looks pretty good! Few things I'd appreciate if you could do:
- Add table headings `Light Mode` and `Dark Mode`
-  Simplify/elaborate the img alt: the commit is from a different repository, it may cause confusion

**Comment by saksham-s1ngh** [comment]
> Looks pretty good! Few things I'd appreciate if you could do:
> - Add table headings `Light Mode` and `Dark Mode`
> -  Simplify/elaborate the img alt: the commit is from a different repository, it may cause confusion

I'll do the headings, but for the alt text could you suggest it? Or I can just make the alt text read "A sample Readme.md"?

**Comment by Akshu-on-github** [comment]
Something similar to:
- "Demo in Light mode"
- "Demo in Dark mode"

Also: please remove the heading (the h2 element) above it

**Comment by saksham-s1ngh** [comment]
I made the required changes, not sure about the alt text though. Also if I make a PR, do the changes made after opening the PR show up in the same?🧐

**Comment by Akshu-on-github** [comment]
> I made the required changes, not sure about the alt text though

The alt text looks fine, as do the rest of the changes. Will merge it soon

> Also if I make a PR, do the changes made AFTER opening the PR show up in the same?🧐

If you make it on the same branch as the PR, then yes - you've done just that, so everything's a-okay

**Review by Akshu-on-github — APPROVED** [review]
LGTM ✅ 
Thanks for making the requested changes 😃

**Pull request merged**
